### ISSUE TITLE
Trimming error when rectifying maps

### ISSUE THREAD

**Issue by asitemade4u** [ropensci/mapscanner#42] opened 2020-10-01 19:02 UTC
- When back from the field, I have scanned the modified map with red markings into a PNG file
- I apply `ms_rectify_map` as described in the deocumentation and I get the error:
```
❯ Converting to spatial format Error in FUN(X[[i]], ...) : !anyNA(x) is not TRUE
In addition: Warning messages:
1: In trim_white(map_original) :
  Attempt to trim white space from image appears to have failed - result may not be reliable. Please manually trim whitespace from [01_mapscanner/dta/01_before/gw.png] to improve results
2: In trim_white(map_modified) :
  Attempt to trim white space from image appears to have failed - result may not be reliable. Please manually trim whitespace from [/tmp/RtmpHyIYsk/imgMuwgWvohJ5.png] to improve results
```
So:
- I trimmed the modified scanned image using an image editor
- and repeated the ms_rectify_map
> same result

I attach the two images for your testing.
![gw_before](https://user-images.githubusercontent.com/11460106/94851906-150e5b80-03f7-11eb-86cc-38f094d895e0.png)
![gw_after-trimmed](https://user-images.githubusercontent.com/11460106/94851914-18094c00-03f7-11eb-9183-0d73eb7cfec8.png)

**Comment by mpadge** [comment] 2020-10-02 10:29
Yeah, thanks for highlight that little bug, which the above commit has fixed. I saw your image there and frankly freaked out a bit, because the package clearly says it is intended to rectify polygons (or points) only, and that there shouldn't be any other marks on the map. But then of course the package should be robust enough to do something regardless, so i tried it anyway. Unsurprisingly, it didn't work, but it did generate bugs that nevertheless shouldn't be there, so I'm going to re-open the issue until they have been resolved. Thanks for using the package and already helping to improve it!

**Comment by mpadge** [comment] 2020-10-02 10:49
Oh no, wait a minute, maybe there is no error - the problem is that github's image uploader strips all metadata away, and these metadata are what is used to rectify the coordinate systems of the maps. I manually re-inserted those, and everything seems good. Trying to call `ms_rectify_maps` then just errors with

>  Items unable to be extracted from map; perhaps try explicitly specifying 'nitems'?

That would be expected, because it is trying to convert everything drawn on there into single polygons, so is bound to go wrong somewhere. You could try for yourself again, this time ensuring that the only things you draw on the map are indeed closed polygons, and all should be good. And the other thing that really mucks that one up are the lines which extend out to the edge of the image and do not form closed polygons. The algorithms tries to close all lines around on themselves, so that can only lead to estimating one huge polygon which encompasses the whole image. You can internally ignore the error and generate the resultant polygon estimates anyway and confirm that this indeed happens (and the result then happens to be rubbish which does not reflect what you've drawn there at all). I think that we can also close this issue again now, but happy for any further feedback at any stage. Thanks!

**Closed as completed by mpadge** 2020-10-02 10:49 UTC
